apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: 2022-01-17T12:48:22Z
  generation: 1
  labels:
    run: web
  name: web
  namespace: myproject
  resourceVersion: "21811"
  selfLink: /apis/apps.openshift.io/v1/namespaces/myproject/deploymentconfigs/web
  uid: c135edd3-7793-11ec-b428-000c29f20211
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    run: web
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: web
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: web
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
